auth:
    local:
        allowedOrigins:
            - ENC[AES256_GCM,data:QkldpBqvUw+I0mPDexbX7ZWu6PRPuyfZ,iv:KXmfplsVToJSs+XO7TnlVtMadPCrg8/lqiHCPZIlxPo=,tag:NX7WzP1xhEXHrxExrLJy+Q==,type:str]
        defaultRedirectOrigin: ENC[AES256_GCM,data:1+EjVKVDIddHoVf0xRUNgrx6YQ8maHSc,iv:6B7SfAP8Ca/BayxqEY5XTNDwnbIocMu8POJChkN4a0c=,tag:wLcLyWxZuP6ivzpyN5kxCA==,type:str]
        redirectPath: ENC[AES256_GCM,data:yIVzgap2bsroHgTU,iv:GCOfscAH3bcm8nXlhwrHo4ZavXPNwQwW1/0klM4nlfs=,tag:1cMlkcpUa+5la3NNZ24Njg==,type:str]
        line:
            channelID: ENC[AES256_GCM,data:/7qYc+QMnL6Jo0TEhT1qKT/dy1c=,iv:8RvMgOnB95GqSVAzhP2+noJIgpgR02s81rm0Ke8o32A=,tag:nA9kW035JzWB1MlX4Lq9ZQ==,type:str]
            channelSecret: ENC[AES256_GCM,data:nLxfDyYeHyFTOQTsekSo/CMscA==,iv:D6m1k8P7GruAjhnOosiVhXR4ebs1wkh3BfAP0EVzTGM=,tag:gQla/qSk+lnbHy58jTAGJQ==,type:str]
            redirectURI: ENC[AES256_GCM,data:kPMYPLr0UH5/Nh6K8q/CH95fFeUdoezCkDSjZXgh3SJCPcyp6GSyUFcOgQ==,iv:oevX+cYwWyVqmnoHmOxMW7eUEkucJ92EpfknWZe7vIs=,tag:u5CBcQbpVk7/hBjlE+FMSw==,type:str]
            scopes:
                - ENC[AES256_GCM,data:1Es8hEtftg==,iv:Qz3L8mZ1jnkF9Px9jBR+NBRJ7wTcdO5f+FulaC7+R8g=,tag:l3BhIwRJaLRArNey6ELkNg==,type:str]
                - ENC[AES256_GCM,data:PEln6CWC,iv:UesK9oSvwazKqGMAjpZAQA/AbobG91t4bhaJFoOUBOU=,tag:9guhg+noW5G/gJVsa6gyXQ==,type:str]
            stateSecret: ENC[AES256_GCM,data:qSUP8P28OD7raKrPUWFNm336dqLOG5Es0A==,iv:YUTqCLD0c/K9kFmvK+aWzXD+CcVc9xLxYjKGu/wEm+8=,tag:T8fVpIj14xPG2sQZpmBsqw==,type:str]
            stateTTL: ENC[AES256_GCM,data:r4wC,iv:9QLNF8qPqgp4/lApP03pwVc9m+nIajpg4OgkGSE1hsw=,tag:EZzy2jIwBgs9WkpvUNqSCQ==,type:str]
            jwtSecret: ENC[AES256_GCM,data:5LPNP97Cm7x4C+3DpmzzBWVwS4ityyU=,iv:MjtH+CJf682tAkFBgMa7Ar0TpSlo6036mqdBM5ILlJM=,tag:VeSAYHiwk4lKggITnlwT9A==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:jw7+D92xV5vw,iv:4ztg0wfEg/qvDhwq0GFEmGiwnuit5dp6Hx5HBPHsCKU=,tag:txSKSkshnmLTGRqIwtI59Q==,type:str]
            jwtAudience: ENC[AES256_GCM,data:jmg/g5+CPLY=,iv:JaMsWkLUwgM7qWPHfgtr3KcurInuKbFQWwUOU8ZQMjw=,tag:H0wtOVvc6n6bwGpvP9oNcQ==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:vpMq,iv:h3IHt76SxXS8dN/JsaUb9Wp7nLEJXifhlccLmSpTodA=,tag:gDeHUh/kdTW5ZSIsXqb9UA==,type:str]
        twitter:
            clientID: ENC[AES256_GCM,data:6kxZ2E5truf0IgZX9Z0t/bwJCWTNwg==,iv:LC+JkBM9sbvHbbTk7hPIiideI3Fc6hCRYdAqz7PwOwE=,tag:GeqQs3XcIGf72Q0OagpwKw==,type:str]
            clientSecret: ENC[AES256_GCM,data:kCd9heKD8+sdzkpt5zNHXYRvXCgQlg==,iv:DFWhJBcbxT3ge8K5V+pf271wsn6MtBQeal3EyIFw0RE=,tag:RucUuEt3O+lFaAEmDwpviA==,type:str]
            redirectURI: ENC[AES256_GCM,data:E5lY5/SiDMokHM2iY+NhaW4QxmeYsrsvH2l6jwDVvvHYkvMsMvAvLZinuZY8zA==,iv:Ava2kSCd6vYH9UCa+0h+EfxqioRBXd1dcwGp6AiRMec=,tag:H9s8Bh1Zj+NaWeB0rgtfBg==,type:str]
            scopes:
                - ENC[AES256_GCM,data:0z7KaFWx839nxw==,iv:xPLEbuPCAbWDqrbCpSs2wZkZMUlA4hwESU5b478Qdtg=,tag:zUoI0SF/fbVQsxixnnab7g==,type:str]
                - ENC[AES256_GCM,data:24GUpBTug3EEEw==,iv:fOQFwAAvYWK7elw2i6cPfCv3YApn7qUcFyeyC910IQ8=,tag:vs90ccK6sDKSgjgFmE35GA==,type:str]
                - ENC[AES256_GCM,data:o9ik02Mb+EqqKeOIVlI=,iv:5zh2c7bz5U7qbtYJqQkzuw+3iW6iRc2rOoHwwdstYGI=,tag:xr/vwJ6eBeQRY/r7aLpsyA==,type:str]
            stateSecret: ENC[AES256_GCM,data:bSkDtKkHF/LkSDp+1NOdYz2Rl5fKxP62vL1j9Q==,iv:IIFU63OGJjkVCLR5vYcElz8SAzGfh/09UPuPL9eHB9A=,tag:WU63w1oAXGIKU+KPKYqZHA==,type:str]
            stateTTL: ENC[AES256_GCM,data:IDO3,iv:OJHkjlr6v1iTF6L2I3zM2eSnW9HHSHZjrhc7qGTBgOU=,tag:SQ3hS0rklaNdm9qn3FncFQ==,type:str]
            jwtSecret: ENC[AES256_GCM,data:3AJdgEHNNxq9DCYwIPl1tehQqRzuS9OJ5cI=,iv:pBtIk+idz+hrN7wy9MOLrdZ76g9fPv9NlaqE8yoaJN8=,tag:pY9Z27LRrFIoXedO9hCI5A==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:hE/QvDMT0E7iijP3,iv:snPT1IUO+0dJqhts1Hm8+137ZihH4AloZD4HzFjyQJ0=,tag:JUGtXteckYkfrwhtFb01Ng==,type:str]
            jwtAudience: ENC[AES256_GCM,data:clOCpG8b4vs=,iv:N/+mPKpzfE+80FMXnLtrNmct5GuxmKx5WiVxYo4egqo=,tag:NFOnTTp1hnBDa28+3FkJNg==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:bUjy,iv:cXhojD39wi0Sat7BUJcPag1qKNJz1tBm4Zr+fvf1z3s=,tag:kIdTJSE47TRA5BQ0G+dloA==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c2Qyd3BoOWNQVWc3R2w0
            NElvVXpWY3ZKdXZEejRWZ1hKTFdXM3ErNkZJCmIySlFLVnArVk5zclJhd3dsQnNz
            cFY2bitBM2xNamxQdzFuOHVnbE5tNEEKLS0tIERhcktqdWtEb2YrK0w2dStIUWtU
            bmRXcVYrVHpQamsyNlBsWW9lS0huTjQKXZnQ3NjPN6m3MqHph/V6pcE9xNJsyh86
            nIVubNDgeWCwiHlPC7ddwfUMOSiwBbzD9QoQFnDxYIKVu2jXvgGAGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:56:55Z"
    mac: ENC[AES256_GCM,data:pi4JlR/p/SbBQztQZ2FKSqiKNDaH2s74zcwdGWh2iQoJbLJhQxIa71OJrkQUHSUQ1rVOnowEs/Vm3j3zf93dmm00XEanEn3bOvhO8Pvv8lxS0Buo4bo2YLTF3WgJo1aCTp+9PiP7990afIdp4ITE51UCK530F6dR0THoHkYLmWo=,iv:CUsv3tW2NGA7vAZaiEDitSDcnl+aWZ9CZ8RFkODw8Gg=,tag:/RtXUhqSa1KwIT8xMh1cxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
