message:
    makotoclub:
        natsURL: ENC[AES256_GCM,data:CeaMbTQ6iPLxfz47+QQsvg==,iv:sC1RuOuguWtgcXB+VlG9LF5MDPce/CoD1/RsHq5fKbI=,tag:fY0SHYP89PnpXSIPeXXfqw==,type:str]
        lineSubject: ENC[AES256_GCM,data:00uueZuw+/IhDd1qiujLg/WsyoiiDw==,iv:xz7tceCjXIAY2LuPPcshHd1/JTR2euf7vezMQEC5qEA=,tag:BOhSa+WaA2/XqTZqqqRcOw==,type:str]
        discordSubject: ENC[AES256_GCM,data:/XO7SMf+lL5pPwkaZtjof9VyhM9NTxWL4VEU,iv:kii7vFaMiB/r6J+eC02msAAfwnbHTmayz8dgcxRmlzY=,tag:WeekdM93IMrZ02yd/GbqmQ==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:wBDhEdYF2oOCweuvYzGD/EJLstvmntS4TP00XNoxpATWZeqVe7Fh,iv:s33dEYLFX+SWpYe5OU/1JPzJkvhphYk+Uj6ZwmvmK1w=,tag:wSlMhn8aYW0OWpCAT8sTmg==,type:str]
            channelToken: ENC[AES256_GCM,data:9pieuU8XWXpm0Wm/sSsotg==,iv:vSL3o9biatMEkklodw5egqkc4QT2ynBUV1rP6Frbfsw=,tag:mL/8wXLXKoBS1F+zasNUgQ==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:HRIkEmfIBIvwCFxg2X6MmSZBcbLPFmchLKduztUzla3me+V7TAE2SOqhr6RMl4+8QOFKYG+TYSdQ76WzpxP4qgh6r3Z9lHK7aa5LIrr7h02kxq8yf6XA6stAFc26p8DMJoaunbf+P4RCtIJyapX6Jn025e7aLmyamA==,iv:tMNOQO7opP5ox4po4r10obVKe/qZYK2Fh5SybnGemOk=,tag:1Nny5RXp0QhprgWzvBd1GA==,type:str]
            username: ENC[AES256_GCM,data:0XADHgCk8F7L9AnRNUM8Kgwx,iv:TldKEUSRYaTHdbCV7m5bPKpTSE7uJt95XaOtr8cmCnA=,tag:3E8Or2uJCxLu+FblUxXrvg==,type:str]
            avatarURL: ""
        defaultDestination: ENC[AES256_GCM,data:hAKKepBZSg==,iv:qN37JZXUCe8WaUUoxuZXZAzjs/Dk3oTXzveVCS8f1OA=,tag:t8aNIM24sreGYk+U7YN+bA==,type:str]
        ingressTimeout: ENC[AES256_GCM,data:J/0=,iv:vk1D5wcfaeEUIBEmoVbHR2SSoijtKRZyZK6v5vywSWk=,tag:Mjq/b5o3ZwxHYRyNeN0gdA==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:aWQ=,iv:+sM+y6pzyDSUse3cWlJqU35iMSc1pUpWrcdqViSW6FM=,tag:cY+c6ctDKColtqmiu3S1tQ==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOU05Zy9LZHNKY25JV2JM
            bmxnTWlvZUhxc2NrNUpZejlVbHpMcHB4WEI4Ci9WZDhiZVBhNHZhTEpWZy9RVzdQ
            MWtqTVNrUkdDWWJGOStsR0RCVHNuZUEKLS0tIDAzdCt3c0NTc01kUHFPZjlxOWV2
            dXJpSWdUanNnWXRLNWdCc1piZXV3bTgKhy2A5v+1mgqvuH6VulMeWDCzqja2LBgp
            AZIBSPj7DGabiiFLhgfBwrTkXL5AEUqKORrbyd4Z1xF4lXv61/vJJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:56:55Z"
    mac: ENC[AES256_GCM,data:OpRkgReVaFL082RTadgCAM/AY/EQa7zStMI2niZVzN3Lm1ImpK17QX8WJPuGIvrEtCTsg9qb0zJW/lKFLmESnfRTybirH8C0rnCCasaFs2zKhG+deFXrQu+tSE7enkQRO5hY3f+EjGA+y4PoNEbSNFdxIgnVIjO54xU+Tysxgcw=,iv:qDQr21mKdjZxW4DSIWF/hsnxBOmIBVeBKsgCfD2Oc2Q=,tag:5UaQk9rqMnHNYGrNgJ85Yg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
