message:
    makotoclub:
        natsURL: ENC[AES256_GCM,data:qIuYf1Jpj6OFg7xKIFwSQg==,iv:jbgt9cySbOROA0bXFgKCXNTXFKCf1bCCmwK5n6HpPBg=,tag:jGAiBpLSL4Ij+ln7fYBlLw==,type:str]
        lineSubject: ENC[AES256_GCM,data:Zym9wSbja4BO+DzAjQikckZxwoBolg==,iv:ovuZuAHFH6jaHtxCMEkCHPT21S2L/joQAT3p2mmyn6Y=,tag:eYB+CRsd5xSYrFn+K+QWMg==,type:str]
        discordSubject: ENC[AES256_GCM,data:ORfhtWAJ29cT2wOryB/hMQSMYgN44AlVEaOF,iv:L6debZExqvuao9ZcRa9+XBMmqLh81/mvcsEvaKRrScM=,tag:/0t0RLhqQYBjp3f7KlgW+A==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:56tAZmttD1KuV1Vb3Sn5F7BcYIQH2MclkWpIT1uzfllBF3TtII0o,iv:FPaQ5G395W6ks9E5bzY8uiIAuGmBP9k5yV373uohYH8=,tag:fKh9CHNbp+IFXsCL7cJWnA==,type:str]
            channelToken: ENC[AES256_GCM,data:yiwihlPbG69A8xhmRoZBcA==,iv:oe6KGlm5AKh7gf4MsD2NaLUsQBB2dGY0z7HJfJcmWJo=,tag:vjs1t1/MQXgY3+kL10oVYg==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:SYMG8WKOhFg5FpoxNjpqEqc/NC3V3vz39SOVG0ZEQ59fD1b3MxDvM2tHsyx8ICFg8ab9zzHN9jgs+Ws0WjQxdAdh8spqI3suMN6omaUTLqc3Ve0XPT5bOOG+nYMsjqT+wb7U4N3JuyGkgA5rCKQN8wQaIOCimQUouw==,iv:HqYWqJd0LSYRlXUczTgSUcf8sfgmIqMxNLgQVRudmdM=,tag:ISotNswhOLLQDi5iY99gKg==,type:str]
            username: ENC[AES256_GCM,data:UXLeON6EywmYoB8doZbHnP+H,iv:WY4jr1PQDoIJf5luE6v5pOWrsEVmO1+nrtIg3zA63Js=,tag:0wYTndhoZyFoeTexQ5Q5TQ==,type:str]
            avatarURL: ""
        defaultDestination: ENC[AES256_GCM,data:pUr3OQuzSg==,iv:d8Ld0I69VPXMwmCfyjf5n33P0gRHf3TnBTM7AK5LXBE=,tag:QONcYwvfdI5PkFRhwxhV2Q==,type:str]
        ingressTimeout: ENC[AES256_GCM,data:akM=,iv:zXIdGhAcGE/jDK2Pyl2GClx2tkWMp8BXES9KUKC0WjU=,tag:pP43UNE/SEpYF95G67fp+Q==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:Rog=,iv:S7R0GhqRxS6Zy6fjsCNCaj0Hv71URbbPiUYmQsqLCH4=,tag:ZtgMO/au/x9vRYFyIXLwlA==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QzBqdDJINGVoeWRnNUhj
            Z3hWcis3bXpBOHZBMzlvYlZDdkhLamdYVXdNCkRXSklhc1hiaW9ZSzk1NWFzd0pC
            cnhvUHFPV3lvdzhLSC9aV0hNdG5tQnMKLS0tIHBZZExlb1NodFNremkrZHJtdjkz
            VitMTWY2eXBDWGNwOHI5bmdpOXZRaE0KeHzj4oJ2OgoqsBTMRxgkTZJqvUhptAmi
            xtN4l9+2gFwZOzOAcTz+zf/yFwcK4eEM/Mv73G/Q2LNRrjeJ2wz0gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:46:33Z"
    mac: ENC[AES256_GCM,data:E3qrxICOvX0P6753x1/9PxDzjpMbiZ4eRAjK283PXm+UnP9hrPso8I5HWq4art5muXWhIBxYV+L/nzJxL+aQYFDaRL7JlOov0q4gJg/gdcLhbKzQhuLIflZcmGELmCH2/kn19KGrvTECqcj6NpuelfKjV/e/n//VULXQI1BFvvU=,iv:tjfpbgzR5sra0SH6Sbl65XOSkzjjT6eQ1j1hoB/maHU=,tag:yNc228APV2WUyIoRqVSB6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
