message:
    sngm3741:
        natsURL: ENC[AES256_GCM,data:noHo5lu390A5eM7pQe401A==,iv:A0BRAD/qtif4C1tLgAC+t42BRAk+kTnflcT/2p3cte0=,tag:bnYF4FAHUMBBcKfwfwxxgA==,type:str]
        lineSubject: ENC[AES256_GCM,data:aCAqylFZ9PW/kCOV5TkAnPQ+xbY=,iv:iB17s3XLYet3NnOAEqgWcKd3tHSlSjb4hMpoELjmJbs=,tag:vthzQ+Onl8Fm6EgqGQLOHA==,type:str]
        discordSubject: ENC[AES256_GCM,data:bAVyzKtBT35vM+FRV5pWiMpYu3Zk3A92Tw==,iv:vA5/Xnihl8DqiZLyDgP5o+UyY7kyX05S9JSpd8+Uumc=,tag:h/mU6GRG3HxPkNmi09ix1Q==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:TpCfZWBliXKbwPX1UDSIkskCPpcTsJvIv3rRSfUdb6eugWxV51yK,iv:4kYW7KheSJ4zn+obIq3lTgeH6tyDwspwG/rP0bVAE9Y=,tag:Uyu0pTz9rlTrN/5k4MLeUA==,type:str]
            channelToken: ENC[AES256_GCM,data:UKPbD8fjkkCY287B8BQAlw==,iv:BSV5so2NiMPPk7RpOTmLDx28IKNJaQs054SPDvV/Djk=,tag:peIv4uQ9bACy3c254laiFw==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:NFn/DBPK2npGd394B/+BVpPSjmHlce++tm0I/5nc3B+AEeKNOjkhFhkhcgW2Gq6jX6ne4bWQW8CgQ8j3HO7W4Avqg4+FUfrYQzPXGBUyUdzrbS1j4XOiokeFfvEgvja2QT9CsRC72cJ1M+kGTpQwylkXJu0VCSXq9Q==,iv:3KH8+biEgbXkvLLn/bvmP2CGIbyjj1ZlI2vDs+K2/+A=,tag:8WPPRO4GrU45r7BLyjX+Dg==,type:str]
            username: ENC[AES256_GCM,data:h9r5y02FyQAo4+O1gHTh8w==,iv:lz0Hz0KxFgHm268CnBT/iw9RPcNzNpzCVZwfbrNtTLU=,tag:RR/cTDFfbNpFBPkECJAVOg==,type:str]
            avatarURL: ""
        ingressTimeout: ENC[AES256_GCM,data:iRo=,iv:i2r5mJIWr3gV+0EEiAX8G2DCaYxuCjaY7pEIBCsfEAA=,tag:8drUWT3sSys7VK5r4il8pw==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:Tuo=,iv:eoL5dtlzSRDUfdfBtuj/mNdNMcfWjql3g+YGypWn0eM=,tag:Hki9KRG829W/6fASFr9sMA==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaktlYitFMytqSFgrL2I5
            d0QvSS8rQ0RRb055UHlGWXEvMFI0dy9LYkhVCkVQbXo1S05rMHA2YUg3cTJObzF2
            a05DMVRpNnNCeGZTeGVFazZGT21sY1EKLS0tIHJFVUJjblFOaUk2aUVNelZQTVBm
            OVlvOE1IZWVDUzEzVmIwQzluSHVYcWMKG02hAc6WmJQeTf4Yh5Nms75x+7O0MGnv
            DR3n6LlzdhJeUQJbdf49qC2q45OdREdfKJXvQAYi2XuZPKHm//m5VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:46:33Z"
    mac: ENC[AES256_GCM,data:IXuWjK3NW3QpLGz/WfbShVqdWzhG4iX3W7vdMpXpMKZp8ZBrpJ74gYNGi/MXesDAje8xEjovUlcaeLotzBqE6aJ6g6M3pFstIVm83gxGm6HuEZdhB4IhkJEI00uqJrdK/dXM+EUNwkX7DmXMpppVicaQCOqUpCOX7cunRSZFKws=,iv:kZy/Tp2lKC5vrhOoEK5znPo3ggIuZTyKiDRZ17SnkCs=,tag:m1fp02A8KwidKH+PXFCkBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
