message:
    sngm3741:
        natsURL: ENC[AES256_GCM,data:tmPubllYbDejB+MOc6ar+g==,iv:8FQWoyZWyK/hIHrNFggExvIhjj22cAOS2IwIjkeWPzc=,tag:BDQ46YcXdIdpdqs2qhNFtg==,type:str]
        lineSubject: ENC[AES256_GCM,data:IiX1AxDOW129wYyOt4Wjir3yPdw=,iv:sFYtnqNZ1OZBn7IikkRGcFmdxPBRKCYZXdjD89c6ywk=,tag:1Yawn6tIzEtdoFzTLIv7qg==,type:str]
        discordSubject: ENC[AES256_GCM,data:NWqHNo9se68N4LO/I9Sl/HE0TcxGTamRMg==,iv:oKII1hiG06NkAQGjp8ipBKAmvHr2bAvWwyTzdX6i3M0=,tag:YOnLRyYR1L1idGAmPQpNBw==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:1z1K3DhgsTduRz8AbbFKfvUMbwAKh22GhKnvMn0zp4FxggQSBHJz,iv:XlwpuERVJ66FaBbQ4kooX5cv5YSoCyxbjRs345crrOY=,tag:mvno1kUUojre3C0CmHMIHw==,type:str]
            channelToken: ENC[AES256_GCM,data:mzM9WqAqNaCVJEKJiCd1Cw==,iv:SVN5F+YaganduDVMHWzxBOewM2eO6d5YWuWOSWRXaRQ=,tag:5zgbieSgdUVQBGWfRCO9+Q==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:/fg8qoCiycaa7pvSLoaQ2QnpO5bPWiPPL9w+I9Ky2UQdHbbjbhp9baHRDqgC/fCiCauWNyZ6trr4g0u/mD609iQQksMl9Z1vp38x7l8mGtgzrgN8+8yvkNSs6a6cGcxiY9Fbj5eJy8dG5xV7hAeGfl5R47MX60mvmQ==,iv:3z/qVoI+IMfGAOhbtxH/W4Ig/vJ/NaqjQAS2BM2tyI0=,tag:2SgJAkBovZZKGPYRudqLOw==,type:str]
            username: ENC[AES256_GCM,data:pkFN3QNnOs0we8KanUaBlQ==,iv:1brHii2KerWoCBPiC/0uPIQG6bNFG6gCArb/NpY0s5U=,tag:DnXjqDQvHojp5ILFveJStw==,type:str]
            avatarURL: ""
        ingressTimeout: ENC[AES256_GCM,data:rbo=,iv:WHcH/w+yRw6Eiar7H5Ga7HRbjq5KUXnik9abIvJpIjc=,tag:ks/7paMgrur8nmSYuSr30w==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:eXs=,iv:fispR/Z8sjREES3rW5k4EaHWK24g+zJQfQlntjrZnlI=,tag:iruLpztkxPq2LUeHmv+Jdg==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVkJNeWNmOFkrdXI4UlRz
            dnJtN01ES0x2cXo5N21pTmVwS2VVeUFSaFNjCllWYWFuZGhQbDEweGdaUXorZktk
            VW5kVlVkaEdCRnpqVzQvWmgvWWdZcncKLS0tIDVqd3gxajRDQWJ3cWkzMXk4TlFY
            b2d1d1JRT0ZzRXFQeDFkQUthai9BQlEKuVRIss9BHRrzBsJkZ9DzP7d8lUQQzPXN
            QR+vrNbuDENTlIPP8wXdomRO+DTofNwJRxkXVZffDujBsmQPuNPUBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:56:55Z"
    mac: ENC[AES256_GCM,data:UByzOFGjuS1Prb4uNJZ+SMSfP+HAQrNJb6GL5lWOQpD1EnBWbgNPY/hzSwILQhhG9xOPpkRaEN8/cmsbaeFWZNDx/ux462Hjx2Y/ZDA+x4EppYA0MzsjLKC4/HyXOQLk8IpXd6HNzT1o4zUnqpc1U4k2l/liruaLIfFfqbEOrdc=,iv:ehLxVCS5IX/LUJ7o5vn839cjHOUo8UotGTyuuu510x0=,tag:e8ovy1UVGm5bFCyOF3kbgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
