auth:
    example:
        allowedOrigins:
            - ENC[AES256_GCM,data:EIcvp55f3vcnbND/YEMFRax9cRJkheE=,iv:7pauN0OspTO/sl6izsbxtehRfRYJtVxc0S+lqr96o4Q=,tag:fT7DzvxkM7SLtFeUr+w65Q==,type:str]
        defaultRedirectOrigin: ENC[AES256_GCM,data:qePiMrsytyiGSZMIEddNOGP1jKVOUoo=,iv:7S2pOkLCenS4ja6yUvRv+f6PiM228YAJdtWkscJa/XM=,tag:h20FVEtyERjhQ8uiZFSCng==,type:str]
        redirectPath: ENC[AES256_GCM,data:/bDybQafpmNnwrnt,iv:mxdVFMfHF649Wbu4WdTzBa+J5cpyeW50we59tPjyyAM=,tag:QfgdT+6vm+nNYZfdI+K+yQ==,type:str]
        line:
            channelID: ENC[AES256_GCM,data:IS4wCTvoYq8NlmEFUCWWnfauZQ==,iv:+b3Z8DaUtNrbWL/RgXOqN0jjHSlQFGlBChJtxtrX9lE=,tag:aTHcYt982aBDwrDWPeWEeQ==,type:str]
            channelSecret: ENC[AES256_GCM,data:FsSbGPQXOBAHMGmNFp5QftB7,iv:9WAspcdaPfnDdOs7xNqhyxSqS/ZgHZ1Brs847NbdaMo=,tag:k58LoHjPO3dKac3+gWFhhQ==,type:str]
            redirectURI: ENC[AES256_GCM,data:dCofIMwU6v5ldCI0pEJ/grC29WS9YVoHwVqhJ4QswOzK2OlMpDDzdcgw,iv:RJ0a5lti5DWoUHHSxSRkvMdea4gLNU6bPcdLMaq9ZMI=,tag:D+U2P/NVPIeXEVEekdHl4g==,type:str]
            scopes:
                - ENC[AES256_GCM,data:XtMnMIELzw==,iv:SL8au2Ki7ZzCJX7V1b6pVJCxUDkDWRob2LbMEpS61Ps=,tag:oaEqiSfwULiESWJfFXsRPQ==,type:str]
                - ENC[AES256_GCM,data:u/IeVWwN,iv:S/Jpj2Hz9auPXyJD3C/k8tUW0Pvk/88PsK5Nsww7LbA=,tag:kDdVI3iDDTv0HQ8tk9JC1g==,type:str]
            stateSecret: ENC[AES256_GCM,data:lPKmJtTmxFQppwtcgWUoXFB65rqQfzrd,iv:3xGvYNX0eds09XgG0hdv9s/MIjycgn0BmoQU9uDJL+Q=,tag:78xE6s3TMtpVEofgyq6bDw==,type:str]
            stateTTL: ENC[AES256_GCM,data:VssL,iv:3Y8xjmpHxsnKnfJQ19UG+RTX5O96ZksyDJWqqIKULQM=,tag:u9i5uKYhQscj3XpbTXfKgw==,type:str]
            jwtSecret: ENC[AES256_GCM,data:9xMFtzC2XsHnzZb78cpYETOFUwYz3A==,iv:sPE8lt8PRPcKCqN/PHGq6zmXwBUuJYNwjihZRuwKEyY=,tag:v5i5o34WnU41ACYO6HpFUg==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:s6C4k29d8tvD,iv:V/Kag7cdICzUek9tCXU1I3LxnDRrHUAn6g7qJ4l4dfI=,tag:/Tq+nBiKk2Rxmid6jqUhUg==,type:str]
            jwtAudience: ENC[AES256_GCM,data:uJKsbfZF9A==,iv:cNjzA9iwUO/lMRcyV3Z62eE+q/kkJjXQHfNztkZW1cw=,tag:Wtd71XfsBd0bhCXIUUoTiw==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:qtSG,iv:bS3nAQgWcGCRd5SZ2lX+4qeb9CWoRCt/4X4cFv/bMkw=,tag:CZjXjz53fkg5w5AwQDe5+g==,type:str]
        twitter:
            clientID: ENC[AES256_GCM,data:K5qHkAiFbYcO9AqXwEr899Y1Wm8F,iv:cGvp1Z1xihLHl/iwtrhSt7rkiC1gIqsf0OMsAw9KMi4=,tag:KNegFi5d7/iognVGk9vBhA==,type:str]
            clientSecret: ENC[AES256_GCM,data:Xx4VUG5rOAVlxkxaLFzC/IKQK09E,iv:UJVxv9DCW4zOce1roOdfYTjbHBjJByXTgHsShGmXOps=,tag:9ueVYcnoxe7jzDHmWM5ENA==,type:str]
            redirectURI: ENC[AES256_GCM,data:uk39oGVEhF3geZPDipgBquknNMUqk4GmSm1z1JbJNQKrL3jnD8PAPv8bZu0i,iv:0t3iMrET/r8enfqLG/1zaY4Xd84S6+VZX2G7x878DVE=,tag:wLe7ovNlMgtvoJYVV+CA+g==,type:str]
            scopes:
                - ENC[AES256_GCM,data:DXrEhK1N/j3FNQ==,iv:5cXIZ02PrNsdURE0cGuimsa2T/AP2S5dW9+ogu40vuM=,tag:Zm3qdDaycc4FWQzQazbUjw==,type:str]
            stateSecret: ENC[AES256_GCM,data:9RtvpfpM5XBtud8rbOB8nGB4rMwzRvE7XSD+,iv:LRZWL436gvWXfc2uT7diptXA0VkBkM4xrMJAg2YgE14=,tag:DRse35RiaXQxf4lYYaI5pA==,type:str]
            stateTTL: ENC[AES256_GCM,data:QKHC,iv:jzn4CybPRvUBvzzLxaqEkafrp9gpv41qxaHA8CJGtqU=,tag:aynKmGOwWctbDYJkKFWDpg==,type:str]
            jwtSecret: ENC[AES256_GCM,data:eBNjS+T0F6xBuoGLbZRFPo13gKSw/hdfRQ==,iv:n9uRWcEo2NHoZteKlseNtJF2MuyqnPG0+uXb7dhYmLo=,tag:kkcYgM6DHiK2ye8+b1HWhA==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:AGTbTGdPIJxRMzOw,iv:CEUqmo3hDLyEU5oxkVbVCWEgp/LAYQWuxcBa87xJJ0I=,tag:n6DQjcQSiXIwaDOhn6Tx0w==,type:str]
            jwtAudience: ENC[AES256_GCM,data:4Z+8epSfKg==,iv:U3Q0NGUTTTJlLh+/TEZOEo/DNg4oU/GVRsos/fiOkio=,tag:nMzeAu0HMvV9h/jZ6T7wiw==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:BVjF,iv:WDHlJlVf65TD9JwpK01S/s/RXPvnmRXWut3n90xdzUU=,tag:hSYWGV4NE6zh++68w9hhnw==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZUh3OW9UNkpSUUt3dDVJ
            NkFZeWt3bEd0MTgyNCtRb2dnY3BtejdUVFYwCkFnay8waXNyYXJDZmpvbVpiOEkz
            NUVyck8wYzNOTDFaNERTT3A1QTJUSWcKLS0tIERqR1Z4SU5sQWRVZmhNT09NNTVH
            WW1DcStPUkx1UDg1VFZzbFdJZ1dKd1kKIPRvRkPdhyyPlUguAgHOYYgV9SKuhT3k
            dDuw2YnEdoYkg60lrJC5oWs22RnLRJ0Rl1SwfowUMXfk942G9dx6/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:56:55Z"
    mac: ENC[AES256_GCM,data:QtH565ZzXTymtbLUQEzFwmjD4WDznMZwPnIKCMlPRdpGabf/2qMUSffqaWRCQ27qqWX42O8DxSCH3yRoh6U3tF6wqPGCBZhGDoby9SXLqmeGrbDVaWEQMTt+MUQx5ofb/x5fCh99JK0wWMdj56JtKGYg1oHf1OU/akx/DUDHdSI=,iv:G9DoSA9K4AeVy/BrpVhiXvk44tWdfj6NzORmOUyI4hQ=,tag:WrvI1cds+8bvqAAaboKw3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
