message:
    sngm3741:
        natsURL: ENC[AES256_GCM,data:1sxtgYGPeUxxffO7nf3xZg==,iv:nshdV911qebjk1nQdf1QJBgS8KOgf5h/yiXVN4ffFhA=,tag:+fb5k8wx4G/RvG9R8VKd9w==,type:str]
        lineSubject: ENC[AES256_GCM,data:8CYQnYRlcX6yLO6gQErisllaC+4=,iv:847Tk7L05Imj4FLtpSiiX4CDDjIXB8VIJGK96bzOJ8E=,tag:K2DtDMnKrVgo2jT2vJK2sA==,type:str]
        discordSubject: ENC[AES256_GCM,data:bCD2bFyjRsDTehiYflRgXdKeAU2Xs0kk+g==,iv:dUjxWxBQzQN0HJGE5BDI+wtKJNfsHosDM2rfJTt1z3M=,tag:NrJyG2mM2/sLlR0h1LEynA==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:6xoaRy0Twq+8oPFsz6WQpR4KVICIAMcl/5gdl61Nyp2sB/8L2WHf,iv:UQTS7u8sHwTvWzeDljURiwjWG66GvJBOcxivjQGhkBc=,tag:pTVRR4rHsLgoLitZ87BF8Q==,type:str]
            channelToken: ENC[AES256_GCM,data:IF/870ICrlffQJPUz5c=,iv:X9yekQfmn4IV0NhUIirZRx1/cAQ+Sb5zZIWPgDCZtPQ=,tag:ASf0viOutkFNtMVMVZcbeQ==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:sNeMJheV/2Im+36Y8ZanirZ5qQ7TRZDb0v3BrsmWriSwrLevuULQJntYSkeIfl/oq02zOwO8UhUrKlUqtM8sDkelmeIlfw+QQuFqC8bPT59Gj4BOgR2aYFPUGFOiWE2/8xOQHzlIGZb201pMoWNvyq/GebTBImz/yw==,iv:2Sg43nrPum2Tdd7oMQ7dR6g5C2sYCDG4uUSVWtCxWsA=,tag:pBp8XUF1AUivEm3aa3VC9Q==,type:str]
            username: ENC[AES256_GCM,data:kKd7Y3e+ue/NjW/ef87H+Q==,iv:ayg2LvlbzVoPXMxn39Y/pPc30Ne0gTKTZLULISIrKO4=,tag:jsSM+qpz11XZiP+qJl6cUQ==,type:str]
            avatarURL: ""
        ingressTimeout: ENC[AES256_GCM,data:d8s=,iv:XP/H/6QAjYRHoma5xh9TQ73XXo35xaHKiOKTQzU0q60=,tag:oIO0VkFo3lWdNJyiIu7Ydg==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:8YU=,iv:kXviywr3NzafE+rUbrFm0oY6ElEgPpGRg6Mc01JUI2c=,tag:tW2OdjINlPbe6ckIhdvE9g==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4emtRNUp6SnJpNGRUM2dI
            YnhzMTV4STYzVWNjc0hVV1kya2dFdmhPVHdzCkloL2N5L0xHemZtd1JaalFkN01Z
            NWlIL0UvN3FXamtMM2ZHM3pvYWxUWkkKLS0tIEI5ZUYyODFObGJyejBEYXRkSzdP
            cFM1L3N0VkpDY1pWMnNuYWdLM2FsbWcKrVsH73ycXRqcVmYzuvVXgrhUfC01jw+D
            HyJA2q9jMY6T6uAayzg4Y9hpMLUBhNGXtmJd0467LiqCct4QJ+PaOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:56:55Z"
    mac: ENC[AES256_GCM,data:Y1Hfr4SCew6kfYCVhpk8uworvtzJWeZ8/gUS5shwrVWeZ2kOiWKzsjTIZjQ6/0u/SwXglBCzRnTuFDenC6O1gRd3PX9p91yYNbT3oKwE4KPM09WhaiicxKw0c6XqVw2sjDEUax+C5994HxykkZerGxKaCvSsdt7NJZ77WytsDNQ=,iv:FvJkjc5Mmf15GkBf651hmCGzgI1Bc7fDg+SvRDR+RZA=,tag:bRgIqoERdyCDe4TuQ72+gw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
