auth:
    prod:
        allowedOrigins:
            - ENC[AES256_GCM,data:dd/D6H72qyzDJDIqrKqcEVu9PmsMJw4=,iv:cngFT7ER9IQuP40A0b9oCmPomto8ZbSPovGqpi8dXBE=,tag:LG1Bbi6TgrV/zdMGXVnDkg==,type:str]
        defaultRedirectOrigin: ENC[AES256_GCM,data:e+XuO2hra76dRjjl2jOydXvT05wS0og=,iv:0eNF3OAH4eNhxRTqo0SQ/pKJOljmKePU49n8KCle/II=,tag:reAPGSJoEM8YZfifOl95hA==,type:str]
        redirectPath: ENC[AES256_GCM,data:3hECFp7oDZFuuj0q,iv:6mDwy/xyio3A4ylKwpJEwTT2eO2aqmdmr0EUyXidoT0=,tag:Lw+5C715/qz8/cDCa/F18g==,type:str]
        line:
            channelID: ENC[AES256_GCM,data:EfIX/Z06YssJv/bb/QneX00=,iv:Ewg8Cwb2G/zoQsOOc32CHN328a/SJTNCRg2YzcZ7WRQ=,tag:iQVtZS9UnVizg+4dHuw3Cw==,type:str]
            channelSecret: ENC[AES256_GCM,data:UEKAUOYtkKoOXM8GgpQfiw==,iv:rtXnW2OV5zeGyp1S4Q6DXQT6t3GE86gWIYX26Btp7iE=,tag:J/i2RGFxUzvVy6oSzsMqsQ==,type:str]
            redirectURI: ENC[AES256_GCM,data:rAXUMEeb2MymuXJreRLbdgvdyzXgYc4dwx0Qw78tN+oJQeXatYIrQ5xP,iv:F0/UJmpJMI4cYWez0Aw20o/9VhEvuvXXP1MDqa6eGjA=,tag:81K0EToQaaLCVdwnNMh9ww==,type:str]
            scopes:
                - ENC[AES256_GCM,data:OEE1XECW2Q==,iv:HnEPeGrcEQdp8Gup6TBysTSKA8XqJdjnz2PAsR/DIUE=,tag:0VOZFIRZUoEYPpLU4JCNZg==,type:str]
                - ENC[AES256_GCM,data:kBDgmc1O,iv:nsk3NHWm5OKkeayF5WIdjI20jFljYBGyShfrWduWnlM=,tag:V1mujARnWPEuBcZ2JlP3EA==,type:str]
            stateSecret: ENC[AES256_GCM,data:r++tH4QtVxdvDVZzKW2TglbOR9XF1w==,iv:B83uSZdkIbQmTLGRAPoXPLUA5hZp9ci5EbvOxwdlIP8=,tag:i+JI1OVgKMccZ1i8rxaXLQ==,type:str]
            stateTTL: ENC[AES256_GCM,data:a++n,iv:X2OciM4UfllG4CB7RKYmbqAOK8SHJaa9T1ibIEiXo98=,tag:gHNyD8/d1iE12Z8maMncGA==,type:str]
            jwtSecret: ENC[AES256_GCM,data:V/mHXExzcMqrIe/Fv036bHp05+8=,iv:W9c6e2bTuBi2llrKql9cchp3DypBs9hv+IinZxs7ba8=,tag:Bk5jgzs0QK4G3hFGvZBwzA==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:vFhIAFW1IpJ2,iv:bc6wBy5r3KD35FeAWBGgPDPykKPZqqA7Pj8LXWPNrHM=,tag:THCqH5GFz4RQrnoiv10gUw==,type:str]
            jwtAudience: ENC[AES256_GCM,data:L1dhHyTw7OHB56xZ,iv:o6uW/HuD4uCFGxw2iYhyq/46CfQ0tNwoTry5J0ykyFI=,tag:asd1W5bmLYoZVx8jWT5Wiw==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:0Nv6,iv:fOhS2LOeZhKgwAZnuUhgrenpVYlF0lqig6vbXQ29OdE=,tag:SxUn1u5XfYCY4fbIe/6b7g==,type:str]
        twitter:
            clientID: ENC[AES256_GCM,data:To/FdnyRd0FqxlK1W1enyl29+g==,iv:u7KJEKwiShnvO6hlMg1MHpUWWZ9K9vviDdqlv5LSp9s=,tag:4JS67gVBJtsqLY3zlpFYJQ==,type:str]
            clientSecret: ENC[AES256_GCM,data:6ytQc6sD8qBUkDu18M0qY53kGw==,iv:InBf7eCXqOEiPlGFfwYaHcZFccZs9hLoiWsDYwg+eQI=,tag:aJ25CWsS7tYp+lz7naFT8g==,type:str]
            redirectURI: ENC[AES256_GCM,data:+PZirafalelgduyFsbSD37xUyW2IP/V05n1UkaXDDZLNe6wtGhqVJ19Ne4On,iv:vZWX6cYA8i4VKZJuHKuySYwXx5tA3zLf+1NOs8GIQUY=,tag:ZF6u2V4ysR27xXBx0Try+w==,type:str]
            scopes:
                - ENC[AES256_GCM,data:T6ljIQLEgUHwMg==,iv:ooVCTuO9gLullHInnRsbRxiMV6VEuFE19arz1iyzSFs=,tag:RmGQFvMh6CjPOBYm/3NZWw==,type:str]
            stateSecret: ENC[AES256_GCM,data:CYUkAK40llhKSCwxyjfLbI4/+TjbfSvLGg==,iv:1vq/UyMxX91Isrx3gp0ogP0FnzKUX/Jt2wtGtz5yDMc=,tag:qjjV1r/BEy1ie0A9uWo4UQ==,type:str]
            stateTTL: ENC[AES256_GCM,data:IHg+,iv:KKdrPLeTGLqy/7eIVOdFk+Aw6lTD6mZMo6FU3CBN8yo=,tag:LB+LxfHkt8YtogX+u3E19Q==,type:str]
            jwtSecret: ENC[AES256_GCM,data:UewQNLQD45CXgFXxrweAKd8hbCqg2Fw=,iv:DJVYipu+TbxjsWt5hmqkcP4nz+gaRv7TmgfYr/0B8Mc=,tag:2Dj5FK12yLXG/GrL+TupxQ==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:sjKMsA8kBYbw5JL/,iv:6UulqxybBAhKbGQ/KdRkueh8kOXpkLm9aVbdRS/NOSw=,tag:PABEkKYk8PranSnH0mD2DA==,type:str]
            jwtAudience: ENC[AES256_GCM,data:5ZPDNZ7tFhSB0Mq/,iv:ZKUVBzHq7n4EUHn7RJyO1OrvbFodo8+OYFvC+5IQmiU=,tag:X+W1TK6e81ybI0OrGyXi0A==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:CuJ6,iv:kaLMQkBA0d8JxuwA9RDbqV2avh5Ruen5NycXbYPu0wk=,tag:iHHKgCBPeuljNSNTSjpnuA==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QVUxN1owOU9PSzFKM3Bw
            WXU1aWlXTDJFaGdwMHQ4MHg4OTVQZ0ZBNUEwClA0eFdFbzMzWHhLWE9YQk5FUjJ6
            V3IzSk5iYTMrV0Z3ZmJPSDdQSXNjbTgKLS0tIElHcTF1a0R3Q0NBdTlUaTBFTDNa
            OWlrY2hQeTYxQ1JuYmVSUHJ1WU1GVmcKs0TvevyD7DAnnWtMoeS/hMl1MnwXdHbd
            ZfkBkcaTPoF4dHKugVtEwMlhnEGVKml9YbwA8ryQkhyXQdcv4I5wWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:56:55Z"
    mac: ENC[AES256_GCM,data:LRP/bOrZpXCCHbpuG2dTUpkxRIA/bx/R0e5wkFtRG4UqMvjeB9kRRwwZzVNYaNwGwGCjvS6HHyH/6npUjezRmJTDS5QUaO0xC4jODPd9cHOpuiNmoEFPdaSLCOh8OQQHp4LivuvHFhHHH4e2sAnI34laYaHFg7EXAAWdqlsmKBU=,iv:u6jgpYpBCotokpu6cvgY2ahH4EefgknBj30o+WK/40k=,tag:xT/DfAiw39XxLU2I6OQ8bA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
