message:
    sngm3741:
        natsURL: ENC[AES256_GCM,data:QatolEav5AYbTTNyh+wIMQ==,iv:TSUgLXelMyMe05uKQKYIjYLHuff2U1PMEjVYrwjb3Ao=,tag:k1Ylage8rYt5eObb4VNL3Q==,type:str]
        lineSubject: ENC[AES256_GCM,data:qNy5gBe1rmiYvX3vJVful0ytFJ4=,iv:j/lfaIItYFIE6OGnsuiwPFpRHJhvw6E9CP10sy3UHSA=,tag:xCg6WFHhWA6i63eYDfAceA==,type:str]
        discordSubject: ENC[AES256_GCM,data:yeyplCKnnBWLzv/JLTLo6IPrUuFHlQYh+g==,iv:ez99MZWJA0bmbbcbGqZwtVEFRICeHAYL/WW2MVtS69g=,tag:lj1OXr30S/zHva7OGt9HcA==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:pe1kBEupErYvaunIIGnFm6e7VFU1/4pmymNze+kOhoGJpCosv1Tq,iv:B/z738rABQjdboC+QzHqiDl4BWTEreF1ewtJ8koJGAE=,tag:QXiB3ewPhfW1E09hWVfC9w==,type:str]
            channelToken: ENC[AES256_GCM,data:4+kJT7WGes3Dj+RiQZfS,iv:ADlY4spjMySFiiFYun/r/gGUkxZRKIjNzKu2r8P5YxM=,tag:3/Iw2MTpmd7tchkpFFmASw==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:uEeh8YaQQ9iHhtaN/9YP1DVaGvq9T0xZdTOnz2ZfyP21NOAX6mwA8eC8ecRlVrf9GobNTYpZxN1TXy+fYmJyyeC366/VAdH1FX7f582dMff1rRmw3a8LbmTiWSsIKtiFg1J450/dZt3hhieNlKy1PmMHEcxio8JNSg==,iv:XIXXSG3wGwqLv4Bg9l2HlrpDgHjASCVGkF0PcdNzwH8=,tag:1wVUNVFNkSr2vJk333nDJA==,type:str]
            username: ENC[AES256_GCM,data:bMO7NyhqsHSy30MRqZ3OEA==,iv:MpBErFaCv0okk0MjgeGHXmxkw0fp/wvt6W8o+A0W9z0=,tag:TzgJaQmasimpaw+l6q/SBw==,type:str]
            avatarURL: ""
        ingressTimeout: ENC[AES256_GCM,data:n7c=,iv:I4s8+jLBS3sGDmB2HD0Q1qTx+dWURk+kO/ITHUPxDdA=,tag:lUp5e43rd6TNeR0p3gJHMQ==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:w4I=,iv:RD0oKaF0bEGZ+Mq/G8mJ5bswwzPDVqbCkuheuZZPwfc=,tag:1utRjuD0MUM//Vu9H2iGmg==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ2laZXhpYVJpZEZiUSsw
            NEhhOWY0NnV2M3JLRWdOV0VBaUJZQWt4NWhRClNrYVhodnRpSWFpeExOcmJwMlR5
            K3V2cTJyYzBQS0tXdmZocnk4WExRdGcKLS0tIEVmOEZETk5rakJZekVIZTBid0VG
            NFBlY3ZVM2tyZG1hdkdaaVNNMUUrUmMKCvqV0wUwNWJZAJ7CZDTzLDRfjTq2BbhI
            kMKoZgwyLs771XegrTSY51hdZP4hgiEyzE5skRM2YWjCZxAkPs51pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:56:55Z"
    mac: ENC[AES256_GCM,data:7NaZaG2tpBoAN6KFKoT5iAIfpzfIFVE69M88uomY2wY8ehYi5NhGJBlW9Mr5TWGojZx0iKR6DkvL+rvIHmlx31ir3F/dYtmOIRmfeGWzjXvkO08Y8zwdDNsOvewOBuKlf5dOUAySiVAw8jAHi0u7gdFvy4lUPP+HYZ0vIbfa13M=,iv:A5ZEK+unaBQ6zDbl+dJChyfOK8s3gjihZABKF6SZqDQ=,tag:t+tlZQOVNOtspYotklKbsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
