message:
  prod:
    natsURL: nats://nats:4222
    lineSubject: line.events
    discordSubject: discord.incoming
    line:
      pushEndpoint: https://api.line.me/v2/bot/message/push
      channelToken: prod-line-token
    discord:
      webhookURL: https://discord.com/api/webhooks/1433902116782608544/5UweOpX4v6B2ENNGVvpPqWmoBwYjbNRcC1mqzB4HSEdEqkcB2fyKNBiaj-96nLQJ_1ND
      username: "[自動]prod"
      avatarURL: ""
    defaultDestination: line
    ingressTimeout: 5s
    workerHTTPTimeout: 5s
